### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by JacobKorn** [TEDxAuckland/tedx-auckland-site#11]
In the Speakers section I've brought in the font `Source Code Pro` from google fonts for the captions on the speakers pictures. I also looked on there for `GothamPro` which the designer has used for the headings and body text, but that's not on google fonts. Do you know if we have access to it?

**Comment by GeorgePhillips** [comment]
Gotham has a harsh license. I have chosen an alternative thats free at https://fonts.google.com/specimen/Quicksand
