### ISSUE TITLE
What About Us Section

### ISSUE THREAD

**Issue by thomaspaulin** [TEDxAuckland/tedx-auckland-site#4]
- TEDxAuckland
- Meet the team
- Flickr
- Email subscribe box

**Comment by GeorgePhillips** [comment]
I have finished this section in my rework branch

**Comment by GeorgePhillips** [comment]
![screen shot 2018-04-02 at 6 09 03 pm](https://user-images.githubusercontent.com/435107/38185189-14d608a0-36a1-11e8-98b8-7fe0829bfc39.png)
